# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60105567034ecf6de267e2f00f4df8abe2b7d94c407b71624c32031996168330f3cdba1ff66f9ad75b6f8f060ee88124ca17e8999d55440de59223ab83ea0465

test:
  secret_key_base: 2033718895bcc4a1dc8672cf4e802235a71d0b0e2ec3f1e19d1d058c22c4a7b4eede1c8c2d42a25dff681c821f4f7fc98337312b9ed5badd35402214c158b88c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
